-- Fintech demo schema (10 tables). A few objects exist on purpose so later features
-- have something real to work with — noted inline.

CREATE TABLE currencies (
  code        char(3) PRIMARY KEY,
  name        text     NOT NULL,
  minor_units smallint NOT NULL DEFAULT 2
);

CREATE TABLE customers (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text        NOT NULL UNIQUE,
  full_name  text        NOT NULL,
  country    char(2)     NOT NULL,
  kyc_status text        NOT NULL DEFAULT 'pending'
             CHECK (kyc_status IN ('pending', 'verified', 'rejected')),
  created_at timestamptz NOT NULL
);

CREATE TABLE accounts (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  bigint        NOT NULL REFERENCES customers (id),
  currency     char(3)       NOT NULL REFERENCES currencies (code),
  account_type text          NOT NULL CHECK (account_type IN ('checking', 'savings', 'wallet')),
  balance      numeric(14,2) NOT NULL DEFAULT 0,
  status       text          NOT NULL DEFAULT 'active',
  opened_at    timestamptz   NOT NULL
);
CREATE INDEX accounts_customer_id_idx ON accounts (customer_id);

-- Composite primary key: exercises multi-column chunking in F3.
CREATE TABLE account_limits (
  account_id bigint        NOT NULL REFERENCES accounts (id),
  limit_type text          NOT NULL,
  amount     numeric(14,2) NOT NULL,
  PRIMARY KEY (account_id, limit_type)
);

CREATE TABLE merchants (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text    NOT NULL,
  mcc     char(4) NOT NULL,
  country char(2) NOT NULL
);

CREATE TABLE cards (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint  NOT NULL REFERENCES accounts (id),
  last4      char(4) NOT NULL,
  network    text    NOT NULL CHECK (network IN ('visa', 'mastercard', 'rupay')),
  expires_on date    NOT NULL,
  is_active  boolean NOT NULL DEFAULT true
);
CREATE INDEX cards_account_id_idx ON cards (account_id);

-- The big table (~1M rows): where lock impact and checksum cost actually matter.
CREATE TABLE transactions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id  bigint        NOT NULL REFERENCES accounts (id),
  merchant_id integer       REFERENCES merchants (id),
  amount      numeric(12,2) NOT NULL,
  currency    char(3)       NOT NULL REFERENCES currencies (code),
  kind        text          NOT NULL CHECK (kind IN ('purchase', 'refund', 'transfer', 'fee')),
  status      text          NOT NULL CHECK (status IN ('pending', 'posted', 'reversed')),
  reference   uuid          NOT NULL UNIQUE,
  metadata    jsonb,
  created_at  timestamptz   NOT NULL
);
CREATE INDEX transactions_account_created_idx ON transactions (account_id, created_at);
-- Partial index: F1 must capture the WHERE predicate, F2 must notice if it changes.
CREATE INDEX transactions_pending_idx ON transactions (created_at) WHERE status = 'pending';

-- Double-entry bookkeeping: every transaction produces one debit and one credit.
CREATE TABLE ledger_entries (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint        NOT NULL REFERENCES transactions (id),
  account_id     bigint        NOT NULL REFERENCES accounts (id),
  direction      text          NOT NULL CHECK (direction IN ('debit', 'credit')),
  amount         numeric(12,2) NOT NULL CHECK (amount > 0),
  created_at     timestamptz   NOT NULL
);
CREATE INDEX ledger_entries_transaction_id_idx ON ledger_entries (transaction_id);
CREATE INDEX ledger_entries_account_id_idx ON ledger_entries (account_id);

-- NO primary key on purpose: F3 must fall back to a whole-table hash and say
-- "cannot localize". Also uses double precision to exercise float formatting.
CREATE TABLE fx_rates (
  base  char(3)          NOT NULL,
  quote char(3)          NOT NULL,
  rate  double precision NOT NULL,
  as_of date             NOT NULL
);

CREATE TABLE audit_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity     text        NOT NULL,
  entity_id  bigint      NOT NULL,
  action     text        NOT NULL,
  payload    jsonb       NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX audit_log_entity_idx ON audit_log (entity, entity_id);

-- Standalone sequence (not owned by a column) so F1 has one to introspect.
CREATE SEQUENCE invoice_number_seq START WITH 100000;

-- Objects around the tables, so drift detection has a view, a function, a trigger, an
-- enum type, an extension and row-level security to compare (eval scenarios 24-31).
-- The view avoids accounts.balance and accounts.status, which other scenarios change.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE card_status AS ENUM ('active', 'frozen', 'closed');

CREATE VIEW customer_account_counts AS
  SELECT c.id AS customer_id, c.country, count(a.id) AS accounts
  FROM customers c
  LEFT JOIN accounts a ON a.customer_id = c.id
  GROUP BY c.id, c.country;

-- Only fills created_at when an INSERT leaves it out, so the seed stays deterministic.
CREATE FUNCTION audit_log_set_created_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.created_at IS NULL THEN
    NEW.created_at := now();
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER audit_log_created_at BEFORE INSERT ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_set_created_at();

-- Row-level security with a read-everything policy: every role still sees every row
-- (the read-only role included), but there is a policy to lose or change.
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_log_read ON audit_log FOR SELECT USING (true);
